#!/bin/sh
# Prints the Homebrew formula for one release, for the tap at
# Blaise1030/homebrew-tap (`brew install blaise1030/tap/tabsh`).
# usage: homebrew-formula.sh <version> <dir holding the release's *.tar.gz.sha256 files>
set -eu
version=$1
dir=$2

sha() { cut -d' ' -f1 "$dir/tabsh-v$version-$1.tar.gz.sha256"; }
url() { echo "https://github.com/Blaise1030/tabsh/releases/download/v$version/tabsh-v$version-$1.tar.gz"; }

cat <<EOF
# Generated by .github/scripts/homebrew-formula.sh in Blaise1030/tabsh on each release; don't edit.
class Tabsh < Formula
  desc "Your terminal, in a browser tab"
  homepage "https://tabsh.cc"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url aarch64-apple-darwin)"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$(url x86_64-apple-darwin)"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$(url aarch64-unknown-linux-gnu)"
      sha256 "$(sha aarch64-unknown-linux-gnu)"
    end
    on_intel do
      url "$(url x86_64-unknown-linux-gnu)"
      sha256 "$(sha x86_64-unknown-linux-gnu)"
    end
  end

  def install
    bin.install "tabsh"
  end

  service do
    run opt_bin/"tabsh"
    environment_variables TABSH_NO_BROWSER: "1"
    keep_alive true
    log_path var/"log/tabsh.log"
    error_log_path var/"log/tabsh.log"
  end

  test do
    assert_match "usage:", shell_output("#{bin}/tabsh help")
  end
end
EOF
